unique_ids:
  forms:
    Customers.Customer: DZZRU7BXIPD2UYJPYNYNPQIQLSTX65SH
    Tickets.NewTicket: XH6LDF5WVYZRBY7L6ZW7RN4JDIFFIC7E
    Dashboard.Content.HeadlineStats: DBWU2UQRC5GEM6PJNRKRYECNWVZYJ5DC
    Tickets.NewTicket.Customer.CustomerSearchRow: NEGSCLBIAAP6A7CE4R43M2GUQDSN4RBO
    Tickets.Tickets: OMTOI2RTLP4EYI543MFTDRRQ6UAEF4XL
    Icons.PlusSVG: IVMAD7XGG6PJ7NQWCP7YDBNVOIA2UDMX
    Homepage: 2A5ZUAWFZ76KHXWMLI4UL5X5JRKVIE64
    Tickets.Ticket: DVHICGP2CGK5DCPO3VCFWL5N3JRUEKIC
    Icons.Avatar: 4DCDFMYDMTKN5WJJZ2N332F62ALVUVN3
    Login: JDYKL2RICYLHXITPFUPGVYXDTXGH5C36
    Icons.AvatarBlank: UDWDECOYX5HF6CJQHL4EKPHHG6RD4E6E
    Icons.SignOutSVG: RZUD2LBSBPGW4DOQTZPSQ2KPC4W5UITV
    Icons.AvatarSmall: 3QHVTU7ZVNCFXCUQE6JUX6SPSAFNTIXC
    Dashboard: 34APWRYJM4ZU7VGLI5MRB7IWCIKAARRW
    Icons.SearchSVG: B27LUPSJRMWGHKIXZUPBK2C267AATO2L
    Tickets.NewTicket.Customer: ZALF5NHVB7K5235CXNSWY7PEYCXASBJY
    Customers.CustomerDetailsOverlay: VVO2NEKRJVDLMIQDH4JA4NN45W6G7K5T
    Icons.AvatarTransparent: WKFPCBDU4WB77THFB6BVJSJ4NAYDOKVL
    Icons.TicketsSVG: W3BE7TX5LHPIUQO7HRQCGXUURNHMZ2LH
    Dashboard.Content: SBZ46LNCXFIYVOS33Z4DSAGXK7EZXTK4
    Icons.DashboardSVG: LGW7AVIRIEPZTD5SSSCFCAYTFG37DQ5A
    Tickets.Ticket.Info.Message: U5Y7GII24WIXHO2LW5SZR7HXAIM3VJMU
    Customers.Customers.Letter: NN376W7A6352RSBEWV2CG4BLAYGCCPHQ
    Tickets.Tickets.TicketList.TicketRow: 4J3ZNGMN6CQ6AKDQCLQQM33STW5IBQGM
    Icons.CustomersSVG: JSXDYS3OS6KLIEZNUPM6CCUUHZENX2NC
    Dashboard.Content.ResolutionGraph: QVXXXCK3FDUSRPTRTAPREU2FSKHG5XCU
    Tickets.Tickets.TicketList: PKKAQMZOAPITDOFK6PKTUH7PF5JHNSHV
    Customers.Customers: ISUS26YLIASQ7X4GGL65SXMWYJA53RMO
    Tickets.NewTicket.Details: A2OXFXFEWZIAPKIODKXOYOODQ2WRPHT7
    Customers.Customer.Details: MTBWN57RVD7GAHIRJQC4DKDYRPJ6OPYG
    Icons.UserSVG: NI576LNCUZ45YC3DKHC2FO2HLQAJQEKS
    Customers.Customers.Table.LetterGroup: PUKRB6SOCXLNRHUKXSEU6ILZJHCANO56
    Customers.Customers.Table: ARMDKQ22MRLARMTLBSAYJRCW3ECRCBLD
    Customers.Customer.Details.RecentTicket: O3G5TAV2KGVUFUBXOFAF2O6ZQ5I4JMOL
    Customers.Customers.Table.LetterGroup.CustomerRow: JP5CWTEXV73HGREB7UY2NWZTGYSQT7XS
    Icons.SettingsSVG: X7DJOVAJKCOZLHV2IN25FZLJ7NRZYB5S
    Dashboard.Content.ProgressGraph: KF27O6AROR3ACC5V76XKCDK27P6QVPIG
    Tickets.Ticket.Info: Y2E5HDBAWM4UU5HB7ZWTIBUIDS2QY4PW
  modules:
    Customers: O34FSKGU5GCFN5OB3QFXLDIQOEM5JPXV
    Data: RRMBYYNWGVQITJ4PQYTLQHRROUOJ3RB7
    Icons: 34IHCE7JGHUKBCH76JGASJMGJN7RQXZP
    Tickets: FMNBXOD55PJCJFUOX4FCXJ2XCJIIGYBB
    Tickets.TicketsModule: '1631202249424390320128286.3753'
    Validation: 7UQAU5SOZHFBG2RZKBL7BOJJKTMGSZ3E
  server_modules:
    DataHandlers: '1669202902916399322221454.7201'
  assets:
    grey-background.png: CRJOABJO4QRYO7Y2ZQRKMP4CWZ4IRBFJ
    theme.css: WWBYXJWL7KHSM77MEFA534ZP2RWJ2IJ4
    spinner.png: OVUKAUSCX6TZ7HPJJKU2E2TJPJKQRDHY
    three_slot_overlay.html: QBBKFYUFPCYXQ4P3A6LXCL2TUZAD3GTB
    flex_col_three_slots.html: UOXNAVRKTFBUZSDUX73T7IFYWTXUXUKK
    grey-box.png: RJE2TUXLEYCPJN2G3KN46P7OQJSVS263
    grey-squiggles.png: DGGP4E3HFMVN6CHSTPC6E5C35LCIIR4U
    chev.png: MSWCMCAGL5LDNX5FHSFDPYYWG3L3GFKF
    three_slots.html: UVQ2Y3IEG3RNVXC4PJGEYJHS5HRPK64Y
    homepage.html: ILSPFDLJ4RIH5C7G23ATFYVYK26J7NUY
    two_slots_customers.html: XF4UOQCCFVHUOIF6CBGCIXDZCR6L5V2E
    down-arrow.png: SM4B2WZANYKXXFI4JJRC6TNMFVVHRSFW
    chevron.png: SCU5N47N3GZRGACTFN23MH3FXFZDECQX
    scroll_pane.html: RE5UEL22CRXKQ4EWKXU44RO7L4IVWZGQ
    user.svg: RCDK6LNABNOMNJOUV3VKYSUOJOA7ST6N
    purple-search.png: KGFNCCYLXX2YJWILDAAV3AERTVY6WYWD
    up-arrow.png: VM43M2QYV4WORR5M3LFYVKLHZXKGTRSW
    one_slot_overlay.html: Q4E67QTREWFSIHWVCKQUAOQQASVK5CT5
